import './utils/smoothScroll.js'
import './utils/menu.js'
import './utils/scroll.js'

import './utils/services.js'
import './utils/advantages.js'
import './utils/portfolio.js'
import './utils/mouse.js'
import './utils/team.js'
import './utils/any-swiper.js'
import './utils/detejling-lines.js'
import './utils/changeImagePosition.js'
import './utils/service-more.js'