import './utils/smoothScroll.js' 
import './utils/menu.js'
import './utils/scroll.js'

import './utils/whatsap-btns-links.js'
import './utils/services.js'
import './utils/advantages.js'
import './utils/salon.js'
import './utils/mouse.js'
// import './utils/team.js'
 import './utils/team-new.js'
import './utils/any-swiper.js'
import './utils/detejling-lines.js'
import './utils/changeImagePosition.js'
import './utils/service-more.js'
import './utils/home-services-lines.js'
import './utils/fixed-numbers.js'
import './utils/to-top.js'
 